import fs from 'fs';
import { SchemaInferrer } from '../schema-inferrer.js';
import type { InferredJsonSchema, SchemaField, FieldEvidence } from '../types.js';
import type { SchemaAdapter } from './sql-adapter.js';

/**
 * Adapter that consumes fuzzed JSON samples generated by Schemathesis.
 * Fuzzed traffic is marked with lower evidenceQuality (0.5) to test 
 * how the engine handles ambiguous or adversarial data.
 */
export class FuzzAdapter implements SchemaAdapter {
  private inferrer = new SchemaInferrer();
  private samples: Record<string, unknown>[];

  constructor(samplesOrPath: Record<string, unknown>[] | string) {
    if (typeof samplesOrPath === 'string') {
      const content = fs.readFileSync(samplesOrPath, 'utf8');
      this.samples = JSON.parse(content);
    } else {
      this.samples = samplesOrPath;
    }
  }

  adapt(): InferredJsonSchema {
    if (!this.samples || this.samples.length === 0) {
      return { fields: [], fingerprint: '', sampleCount: 0 };
    }

    const inferred = this.inferrer.infer(this.samples);

    // Adversarial traffic has lower evidence quality to simulate "fuzz" or "dirty" data
    const fieldsWithFuzzEvidence: SchemaField[] = inferred.fields.map(f => {
      const baseEvidence: FieldEvidence = {
        sampleCount: this.samples.length,
        nonNullCount: this.samples.length, // Fuzzers often ensure non-null unless asked
        nullCount: 0,
        uniqueCount: this.samples.length,
        coverageRatio: 1.0,
        placeholderCount: 0,
        placeholderRatio: 0,
        evidenceQuality: 0.5 // 🚩 KEY: MARKED AS ADVERSARIAL/UNTRUSTED
      };

      return {
        ...f,
        node: {
          ...f.node,
          evidence: baseEvidence
        }
      };
    });

    return {
      ...inferred,
      fields: fieldsWithFuzzEvidence,
      sampleCount: this.samples.length
    };
  }
}
