/**
 * Ecommerce API route tests
 *
 * Mount platformRouter on a bare Express app.
 * - container.ts mocked → avoids transitive deps (operation-engine, pg, etc.)
 * - auth middleware mocked → no JWT round-trip needed
 * - EcommerceService runs with real InMemory stores — no mocks on the service itself
 */

import express from 'express';
import { describe, it, expect, vi } from 'vitest';
import request from 'supertest';
import { InMemorySnapshotStore } from '@integrax/snapshot-store';
import { InMemoryEventBus } from '@integrax/event-bus';
import { InMemoryTimelineStore } from '@integrax/timeline';
import { EcommerceService } from '@integrax/module-ecommerce';

// ─── Service under test ───────────────────────────────────────────────────────

const store = new InMemorySnapshotStore();
const bus = new InMemoryEventBus();
const timeline = new InMemoryTimelineStore();
const ecommerceService = new EcommerceService(store, bus, timeline, null);

// ─── Mocks ───────────────────────────────────────────────────────────────────

vi.mock('../platform/container.js', () => ({
  ecommerceService,
  ordersService: {},
  inventoryService: {},
  billingService: {},
  catalogService: {},
  paymentsService: {},
  consistencyInspector: {},
  snapshotStore: store,
  eventBus: bus,
  timelineStore: timeline,
  connectorRegistry: {},
  facadeResolver: {},
  commandRegistry: {},
  orchestrator: {},
  pollingScheduler: {},
  registerTenantPolling: vi.fn(),
  operationEngine: {},
  identityAliasStore: {},
  approvalStore: {},
}));

let currentRole = 'operator';

vi.mock('../middleware/auth.js', () => ({
  requireAuth: (req: express.Request, _res: express.Response, next: express.NextFunction) => {
    req.user = { id: 'u1', email: 'e2e@test.com', role: currentRole as 'operator', tenantId: null };
    next();
  },
  requireRole:
    (...roles: string[]) =>
    (req: express.Request, res: express.Response, next: express.NextFunction) => {
      if (!roles.includes(currentRole)) {
        res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'Forbidden' } });
        return;
      }
      next();
    },
}));

// ─── App ─────────────────────────────────────────────────────────────────────

const { platformRouter } = await import('../routes/platform.js');

const app = express();
app.use(express.json());
app.use('/api', platformRouter);
app.use(
  (err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    const msg = err instanceof Error ? err.message : String(err);
    res.status(500).json({ success: false, error: { code: 'INTERNAL', message: msg } });
  },
);

const TENANT = 'tenant-e2e';
const base = `/api/tenants/${TENANT}/ecommerce`;

// Minimal valid catalog item body (id auto-generated by service)
function catalogBody(sku: string, variants: unknown[] = []) {
  return {
    externalIds: [{ system: 'test', id: sku }],
    sku,
    title: `Product ${sku}`,
    handle: sku.toLowerCase(),
    price: 100,
    currency: 'ARS',
    status: 'published',
    variants,
    sourceSystem: 'test',
    createdAt: new Date().toISOString(),
  };
}

// Variant with proper prices array
function variantBody(id: string, sku: string, amount = 100) {
  return {
    id,
    catalogItemId: '',
    sku,
    title: 'Default',
    prices: [{ id: `price_${id}`, variantId: id, currency: 'ARS', amount }],
  };
}

// ─── Catalog ──────────────────────────────────────────────────────────────────

describe('GET /catalog', () => {
  it('returns list (may be empty or contain prior items)', async () => {
    const res = await request(app).get(`${base}/catalog`);
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.data)).toBe(true);
  });

  it('viewer cannot POST /catalog/ingest', async () => {
    currentRole = 'viewer';
    const res = await request(app).post(`${base}/catalog/ingest`).send(catalogBody('VIEW-SKU'));
    expect(res.status).toBe(403);
    currentRole = 'operator';
  });
});

describe('POST /catalog/ingest', () => {
  it('returns 201 with item including tenantId', async () => {
    const res = await request(app)
      .post(`${base}/catalog/ingest`)
      .send(catalogBody('SKU-001'));
    expect(res.status).toBe(201);
    expect(res.body.data.sku).toBe('SKU-001');
    expect(res.body.data.tenantId).toBe(TENANT);
    expect(typeof res.body.data.id).toBe('string');
  });

  it('ingested item appears in list', async () => {
    await request(app).post(`${base}/catalog/ingest`).send(catalogBody('SKU-LIST'));
    const res = await request(app).get(`${base}/catalog`);
    const skus = (res.body.data as Array<{ sku: string }>).map((i) => i.sku);
    expect(skus).toContain('SKU-LIST');
  });
});

describe('GET /catalog/:id', () => {
  it('returns item by id', async () => {
    const ingest = await request(app).post(`${base}/catalog/ingest`).send(catalogBody('SKU-BY-ID'));
    const id: string = ingest.body.data.id as string;

    const res = await request(app).get(`${base}/catalog/${id}`);
    expect(res.status).toBe(200);
    expect(res.body.data.id).toBe(id);
  });

  it('returns 404 for unknown id', async () => {
    const res = await request(app).get(`${base}/catalog/nonexistent-xyz`);
    expect(res.status).toBe(404);
  });
});

// ─── Carts ────────────────────────────────────────────────────────────────────

describe('Carts', () => {
  it('POST /carts → 201 with empty lineItems', async () => {
    const res = await request(app).post(`${base}/carts`).send({ email: 'buyer@test.com' });
    expect(res.status).toBe(201);
    expect(res.body.data.tenantId).toBe(TENANT);
    expect(res.body.data.lineItems).toEqual([]);
  });

  it('GET /carts/:cartId → 200 for existing cart', async () => {
    const create = await request(app).post(`${base}/carts`).send({});
    const cartId: string = create.body.data.id as string;

    const res = await request(app).get(`${base}/carts/${cartId}`);
    expect(res.status).toBe(200);
    expect(res.body.data.id).toBe(cartId);
  });

  it('GET /carts/:cartId → 404 for unknown cart', async () => {
    const res = await request(app).get(`${base}/carts/no-such-cart`);
    expect(res.status).toBe(404);
  });

  it('POST /carts/:cartId/items → adds line item', async () => {
    const varId = 'var-add-test';
    const ingest = await request(app)
      .post(`${base}/catalog/ingest`)
      .send(catalogBody('SKU-CART-ADD', [variantBody(varId, 'SKU-CART-V1', 50)]));
    expect(ingest.status).toBe(201);

    const cart = await request(app).post(`${base}/carts`).send({});
    const cartId: string = cart.body.data.id as string;

    const res = await request(app)
      .post(`${base}/carts/${cartId}/items`)
      .send({ variantId: varId, quantity: 2 });
    expect(res.status).toBe(200);
    expect(res.body.data.lineItems).toHaveLength(1);
    expect(res.body.data.lineItems[0].quantity).toBe(2);
  });

  it('PATCH /carts/:cartId/items/:lineItemId → updates quantity', async () => {
    const varId = 'var-upd-test';
    await request(app).post(`${base}/catalog/ingest`).send(catalogBody('SKU-CART-UPD', [variantBody(varId, 'SKU-UPD-V1', 20)]));

    const cart = await request(app).post(`${base}/carts`).send({});
    const cartId: string = cart.body.data.id as string;
    const addRes = await request(app).post(`${base}/carts/${cartId}/items`).send({ variantId: varId, quantity: 1 });
    const lineItemId: string = addRes.body.data.lineItems[0].id as string;

    const res = await request(app)
      .patch(`${base}/carts/${cartId}/items/${lineItemId}`)
      .send({ quantity: 5 });
    expect(res.status).toBe(200);
    expect(res.body.data.lineItems[0].quantity).toBe(5);
  });

  it('DELETE /carts/:cartId/items/:lineItemId → removes item', async () => {
    const varId = 'var-del-test';
    await request(app).post(`${base}/catalog/ingest`).send(catalogBody('SKU-CART-DEL', [variantBody(varId, 'SKU-DEL-V1', 30)]));

    const cart = await request(app).post(`${base}/carts`).send({});
    const cartId: string = cart.body.data.id as string;
    const addRes = await request(app).post(`${base}/carts/${cartId}/items`).send({ variantId: varId, quantity: 1 });
    const lineItemId: string = addRes.body.data.lineItems[0].id as string;

    const res = await request(app).delete(`${base}/carts/${cartId}/items/${lineItemId}`);
    expect(res.status).toBe(200);
    expect(res.body.data.lineItems).toHaveLength(0);
  });

  it('PATCH /carts/:cartId/shipping-address → updates address', async () => {
    const cart = await request(app).post(`${base}/carts`).send({});
    const cartId: string = cart.body.data.id as string;

    const res = await request(app)
      .patch(`${base}/carts/${cartId}/shipping-address`)
      .send({ firstName: 'Juan', lastName: 'Perez', address1: 'Av. Corrientes 1234', city: 'CABA', country: 'AR' });
    expect(res.status).toBe(200);
    expect(res.body.data.shippingAddress?.city).toBe('CABA');
  });
});

// ─── Discounts ────────────────────────────────────────────────────────────────

describe('Discounts', () => {
  it('GET /discounts → returns list', async () => {
    const res = await request(app).get(`${base}/discounts`);
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body.data)).toBe(true);
  });

  it('POST /discounts → 201 for tenant_admin', async () => {
    currentRole = 'tenant_admin';
    const res = await request(app)
      .post(`${base}/discounts`)
      .send({ code: 'SAVE10', type: 'percentage', value: 10, currency: 'ARS' });
    currentRole = 'operator';
    expect(res.status).toBe(201);
    expect(res.body.data.code).toBe('SAVE10');
  });

  it('POST /discounts → 403 for operator', async () => {
    const res = await request(app)
      .post(`${base}/discounts`)
      .send({ code: 'NOPE', type: 'percentage', value: 5, currency: 'ARS' });
    expect(res.status).toBe(403);
  });

  it('created discount appears in list', async () => {
    const res = await request(app).get(`${base}/discounts`);
    const codes = (res.body.data as Array<{ code: string }>).map((d) => d.code);
    expect(codes).toContain('SAVE10');
  });
});

// ─── Customers ────────────────────────────────────────────────────────────────

describe('Customers', () => {
  it('POST /customers → 201', async () => {
    const res = await request(app)
      .post(`${base}/customers`)
      .send({ email: 'cliente@test.com', firstName: 'Maria', lastName: 'Lopez' });
    expect(res.status).toBe(201);
    expect(res.body.data.email).toBe('cliente@test.com');
  });

  it('GET /customers/:id → 200', async () => {
    const create = await request(app)
      .post(`${base}/customers`)
      .send({ email: 'otro@test.com', firstName: 'Pedro', lastName: 'Gomez' });
    const id: string = create.body.data.id as string;

    const res = await request(app).get(`${base}/customers/${id}`);
    expect(res.status).toBe(200);
    expect(res.body.data.id).toBe(id);
  });

  it('GET /customers/:id → 404 for unknown', async () => {
    const res = await request(app).get(`${base}/customers/no-such`);
    expect(res.status).toBe(404);
  });

  it('PATCH /customers/:id → updates field', async () => {
    const create = await request(app)
      .post(`${base}/customers`)
      .send({ email: 'update@test.com', firstName: 'Ana', lastName: 'Garcia' });
    const id: string = create.body.data.id as string;

    const res = await request(app).patch(`${base}/customers/${id}`).send({ firstName: 'Analia' });
    expect(res.status).toBe(200);
    expect(res.body.data.firstName).toBe('Analia');
  });
});

// ─── Checkout ─────────────────────────────────────────────────────────────────

describe('Checkout', () => {
  it('POST /carts/:cartId/checkout → 201 with payment_required session', async () => {
    const cart = await request(app).post(`${base}/carts`).send({});
    const cartId: string = cart.body.data.id as string;

    const res = await request(app).post(`${base}/carts/${cartId}/checkout`).send({});
    expect(res.status).toBe(201);
    expect(res.body.data.cartId).toBe(cartId);
    expect(res.body.data.status).toBe('payment_required');
  });
});

// ─── Fulfillment ──────────────────────────────────────────────────────────────

describe('Fulfillment', () => {
  it('POST /fulfillment → 202 queued', async () => {
    const res = await request(app).post(`${base}/fulfillment`).send({ orderId: 'ord-1', items: [] });
    expect(res.status).toBe(202);
    expect(res.body.data.queued).toBe(true);
  });
});
