/** Spanish synonyms — shared across all Spanish-speaking countries. */
export const ES_COMMON_SYNONYM_PAIRS: Array<[string, string]> = [
  ['id', 'codigo'], ['id', 'identificador'], ['id', 'numero'], ['id', 'nro'],
  ['codigo', 'code'], ['codigo', 'identificador'],
  ['nombre', 'name'], ['nombre', 'first_name'], ['nombre', 'fname'],
  ['apellido', 'last_name'], ['apellido', 'lname'],
  ['cliente', 'customer'], ['cliente', 'buyer'],
  ['proveedor', 'supplier'], ['proveedor', 'vendor'],
  ['monto', 'amount'], ['monto', 'importe'], ['monto', 'total'],
  ['precio', 'price'], ['precio', 'rate'],
  ['valor', 'amount'], ['valor', 'monto'], ['valor', 'value'],
  ['importe', 'amount'], ['importe', 'monto'],
  ['fecha', 'date'], ['fecha_creacion', 'created_at'], ['fecha_actualizacion', 'updated_at'],
  ['email', 'correo'],
  ['telefono', 'phone'], ['telefono', 'mobile'],
  ['direccion', 'address'], ['calle', 'street'],
  ['factura', 'invoice'], ['pedido', 'order'], ['orden', 'order'],
  ['producto', 'product'], ['articulo', 'item'],
  ['cantidad', 'quantity'], ['cantidad', 'qty'],
  ['estado', 'status'], ['estado', 'state'],
  ['moneda', 'currency'], ['moneda', 'currency_code'],
  ['descripcion', 'description'], ['descripcion', 'detail'],
  ['tipo', 'type'], ['tipo', 'kind'],
];
